In [2]:
import numpy as np
a= np.random.randn(5)
print(a)

[ 0.62813374  2.47775829 -1.01664443  0.2552363  -0.4724007 ]


In [3]:
print(a.shape)#rank1 array and not use this pl

(5,)


In [4]:
print(a.T)

[ 0.62813374  2.47775829 -1.01664443  0.2552363  -0.4724007 ]


In [5]:
print(np.dot(a,a.T))

7.855712007576736


In [6]:
a = np.random.randn(5,1)
print(a) # behave like coloumn vectors

[[ 0.55922276]
 [ 1.19036226]
 [-0.90115643]
 [ 1.26442745]
 [-0.15307414]]


In [7]:
print(a.T)

[[ 0.55922276  1.19036226 -0.90115643  1.26442745 -0.15307414]]


In [8]:
print(np.dot(a,a.T))

[[ 0.3127301   0.66567767 -0.50394719  0.70709661 -0.08560254]
 [ 0.66567767  1.41696232 -1.07270261  1.50512672 -0.18221368]
 [-0.50394719 -1.07270261  0.81208291 -1.13944693  0.13794374]
 [ 0.70709661  1.50512672 -1.13944693  1.59877678 -0.19355114]
 [-0.08560254 -0.18221368  0.13794374 -0.19355114  0.02343169]]


In [10]:
assert(a.shape==(5,1))